SOURCES=$(wildcard *.c)
OBJECTS=$(patsubst %.c,%.o,$(SOURCES))
TARGET=dwengo.lib

SDCC_C=sdcc-sdcc
GPLIB=gplib

CFLAGS=-c -Wp-Wall --use-non-free -mpic16 -p18f4550 --optimize-cmp --optimize-df

all: check $(TARGET)

check:
	@which $(SDCC_C)
	@which $(GPLIB)

%.o: %.c
	${SDCC_C} $(CFLAGS) $<

$(TARGET): $(OBJECTS)
	rm -f $(TARGET)
	${GPLIB} -c $(TARGET) $(OBJECTS)

clean:
	rm -f *.o *.asm *.lst $(TARGET)
